name: Grype scan

on:
  workflow_call:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Grype-Scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      
    - name: Running a scan with an json file as an output
      uses: anchore/scan-action@v3
      id: scan
      with:
        fail-build: false
        add-cpes-if-none: true
        output-format:  json
        
    - name: Running a scan with an sarif file as an output
      uses: anchore/scan-action@v3
      id: scan2
      with:
        fail-build: false
        add-cpes-if-none: true
        output-format:  sarif
        
    - name: Save the json vulnerability report to an artifact
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: grype_results.json
        path: ${{ steps.scan.outputs.json }}  
        
    - name: Upload vulnerability report to github security scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan2.outputs.sarif }}  
      
      
      
    