name: Snyk Security

on:
  workflow_call:
    secrets:
      SNYK_TOKEN: 
        required: true
  push: 
    branches: ["main" ]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        env:
        # This is where you will need to introduce the Snyk API token created with your Snyk account
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Authenticating snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        
        # Use || true to not fail the pipeline
      - name: Snyk Code test
        run: snyk test --all-projects --json > snyk_results.json || true

      - name: Snyk Code test
        run: snyk test --all-projects --sarif > snyk-code.sarif || true

      - name: Save the json file vulnerability report
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: snyk_results.json
          path: ./snyk_results.json
        
        # Push the Snyk Code results into GitHub Code Scanning tab
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
      